### PR TITLE
Revamp NewCommand and improve ErrorMessages

### LINKED ISSUE #348: [PE-D] (UI) Error messages are not displayed
Error messages are not displayed, so it can get frustrating if the user does not refer to the user guide.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: beatricetay/ped#2

### LINKED ISSUE #376: [PE-D] Rxception not handled
There is no error message shown when the user miss a parameter.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Kangwkk/ped#2

### LINKED ISSUE #431: Improve Error handling
Provide better Error message for user to decipher what went wrong.

### PR DESCRIPTION
**Pull request by ljiazh3ng**
resolves #431, #430 

This PR:
- [x] Remove `Body` from NewCommand
- [x] Improve ErrorMessages to provide a better understanding on what went wrong.
- [x] Set response text for Error Message.

P.S : Sorry for not separating this into 2 PR.

### CODE REVIEW

File: src/main/java/com/notably/logic/parser/DeleteCommandParser.java [hunk 1]
```diff
@@ -37,7 +41,7 @@ public DeleteCommandParser(Model notablyModel, CorrectionEngine<AbsolutePath> pa
                 || !argMultimap.getPreamble().isEmpty()) {
             title = args.trim();
             if (title.isEmpty()) {
-                throw new ParseException("Path cannot be empty");
+                throw new ParseException(ERROR_EMPTY_PATH);
             }
```
Comment (kevinputera) [inline src/main/java/com/notably/logic/parser/DeleteCommandParser.java]: Actually, i'd say we move this `title.isEmpty()` check after the `if-else` block. This is because, even if you extract the title of the `argMultimap`, it can be empty!

Comment (kevinputera) [reply src/main/java/com/notably/logic/parser/DeleteCommandParser.java]: Same thing for other `CommandParser`s!

**Review by kevinputera — COMMENTED** [review]
Overall, LGTM! Some comments below. I think it's better to sync up with @johannagwan though on the error message to display to the user so that both suggestions and parser work together cohesively!

@johannagwan Please help review!

File: src/main/java/com/notably/logic/parser/DeleteCommandParser.java (hunk 1 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/parser/DeleteCommandParser.java]: Done!

File: src/main/java/com/notably/logic/parser/DeleteCommandParser.java [hunk 2]
```diff
@@ -16,6 +16,10 @@
  * Parses input arguments and creates a new DeleteCommand object
  */
 public class DeleteCommandParser implements CommandParser<DeleteCommand> {
+    private static final String ERROR_EMPTY_PATH = "A empty Path is detected please enter a valid Path. "
```
Comment (johannagwan) [inline src/main/java/com/notably/logic/parser/DeleteCommandParser.java]: Maybe we can just say "Path cannot be empty. To see.."?

Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/parser/DeleteCommandParser.java]: Should i redirect them to `help` ?  Not really sure what kind of information will be available there show the user a link of the UG, or does it condense some of the info ?

File: src/main/java/com/notably/logic/parser/DeleteCommandParser.java [hunk 3]
```diff
@@ -36,17 +40,18 @@ public DeleteCommandParser(Model notablyModel, CorrectionEngine<AbsolutePath> pa
...
                 || !argMultimap.getPreamble().isEmpty()) {
             title = args.trim();
-            if (title.isEmpty()) {
-                throw new ParseException("Path cannot be empty");
-            }
         } else {
             title = argMultimap.getValue(PREFIX_TITLE).get();
         }
 
+        if (title.isEmpty()) {
```
Comment (johannagwan) [inline src/main/java/com/notably/logic/parser/DeleteCommandParser.java:47]: Actually, since we don't allow whitespace for title, we should use `isBlank()` here. This is because `<whitespace>` is considered not empty, but it is blank.

https://stackoverflow.com/questions/23419087/stringutils-isblank-vs-string-isempty

File: src/main/java/com/notably/logic/parser/DeleteCommandParser.java (hunk 2 above)
Comment (kevinputera) [reply src/main/java/com/notably/logic/parser/DeleteCommandParser.java]: I don't think you need to redirect to help tbh, just my thoughts!

File: src/main/java/com/notably/logic/parser/DeleteCommandParser.java (hunk 3 above)
Comment (kevinputera) [reply src/main/java/com/notably/logic/parser/DeleteCommandParser.java:47]: I agree with Johanna, since that makes your intention more explicit. However, technically speaking, using `title.isEmpty()` doesn't matter here! The title's content would have been trimmed by the time it reaches here.

File: src/main/java/com/notably/logic/parser/OpenCommandParser.java [hunk 4]
```diff
@@ -16,6 +16,11 @@
  * Represent a Parser for OpenCommand.
  */
 public class OpenCommandParser implements CommandParser<OpenCommand> {
+    private static final String ERROR_PATH = "The Path \"%s\" does not exist in the storage. "
+            + "Please provide a valid Path";
+    private static final String ERROR_EMPTY_PATH = "Empty Path detected. "
+            + "Please provide a valid Path";
```
Comment (johannagwan) [inline src/main/java/com/notably/logic/parser/OpenCommandParser.java]: Nit: maybe we can just say "Path cannot be empty. Please provide a valid path."? What do you think? And I'm not really sure why you capitalise the word "Path" too (for everything) actually, but it's up to you I think it's no biggie.

File: src/main/java/com/notably/logic/parser/OpenCommandParser.java [hunk 5]
```diff
@@ -38,7 +43,7 @@ public OpenCommandParser(Model notablyModel, CorrectionEngine<AbsolutePath> path
                 || !argMultimap.getPreamble().isEmpty()) {
             titles = args.trim();
```
Comment (johannagwan) [inline src/main/java/com/notably/logic/parser/OpenCommandParser.java:44]: Do you want to rename `titles` as `title`, since it is actually just 1 title (which may consist of multiple String)?

Comment (johannagwan) [reply src/main/java/com/notably/logic/parser/OpenCommandParser.java:44]: Sorry for not nitpicking this earlier, but can just use replace all feature hehe

File: src/main/java/com/notably/logic/parser/ParserUtil.java [hunk 6]
```diff
@@ -10,7 +10,8 @@
  * Contains utility methods used for parsing strings in the various *Parser classes.
  */
 public class ParserUtil {
-
+    private static final String ERROR_PATH = "The input \"%s\" is not valid Path. "
```
Comment (johannagwan) [inline src/main/java/com/notably/logic/parser/ParserUtil.java]: `not **a** valid path` or `The path \"%s\" is invalid`? Sorry I'm just being a grammar nazi here hehe.

**Review by johannagwan — APPROVED** [review]
LGTM! Just a few comments.

File: src/main/java/com/notably/logic/parser/ParserUtil.java (hunk 6 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/parser/ParserUtil.java]: oh yes i'll change this

File: src/main/java/com/notably/logic/parser/OpenCommandParser.java (hunk 5 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/parser/OpenCommandParser.java:44]: Oh i thought a path can have many titles.
