### PR TITLE
Catch title exception

### LINKED ISSUE #323: [Bug] Unhandled edge case for note starting with '/'
Expected behavior should be a helpful message. Let's see how we can better handle such IllegalArgumentException. Should not appear as a bug in the console

See the error log in the image below. (click to enlarge)

Screen Shot 2020-04-01 at 2 04 55 PM

### PR DESCRIPTION
**Pull request by ljiazh3ng**
Resolves #323
This PR catches the illegal argument exception.

### CODE REVIEW

File: src/main/java/com/notably/logic/parser/NewCommandParser.java [hunk 1]
```diff
@@ -52,7 +52,12 @@ public NewCommandParser(Model notablyModel) {
...
         AbsolutePath path = ParserUtil.createAbsolutePath(title, notablyModel.getCurrentlyOpenPath());
-        Block block = new BlockImpl(new Title(title), new Body(body));
+        Block block;
+        try {
+            block = new BlockImpl(new Title(title), new Body(body));
+        } catch (IllegalArgumentException ex) {
+            throw new ParseException(ex.getMessage());
+        }
 
         List<Command> commands = new ArrayList<>();
```
Comment (HemanshuGandhi) [inline src/main/java/com/notably/logic/parser/NewCommandParser.java:62]: You want to do a defensive check that block is not null?

**Review by HemanshuGandhi — APPROVED** [review]

File: src/main/java/com/notably/logic/parser/NewCommandParser.java (hunk 1 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/parser/NewCommandParser.java:62]: good point, i've added a check for null . Thank you !
