### PR TITLE
Absolute and Relative paths

### LINKED ISSUE #96: Revamp Path object
### Why + How

Currently, the `Path` class resides under the `com.notably.model.block` package and provides an abstraction for a path string, e.g. `"/root/CS2103T/project"`. Nevertheless, the current abstraction is not really suitable for our use case. I'll explain more in the following sections:

1. As it happens, `Path` is used heavily not only in the classes in `com.notably.model.block` package, but also in the `CorrectionEngine`, `Parser`, and `SuggestionEngine` classes, all of which belong to the `Logic` layer.
   - To tackle this, let's move the path-related classes to the `com.notably.commons.core.path` package.

2. For now, we're using a boolean `isAbsolute` flag to determine whether or not a `Path` represents an absolute path (as an illustration, `"/root/CS2103T/project"` is absolute, while `"../CS2103/project"` is relative). However, I realized that we need to differentiate `AbsolutePath` and `RelativePath` better, as there is some particular logic that is useful for one but not the other. In addition, both `AbsolutePath` and `RelativePath` serve their own respective purpose in the context of our application (more on this below).
    - I propose that we proceed with the following implementations:
    - ```java
      interface AbsolutePath {
        /** Tests a plain string to see if it is a valid absolute path */
        static boolean isValidAbsolutePath(String absolutePathString);

        /** Creates an AbsolutePath instance from plain text, e.g. "/root/CS2103T/project" */
        static AbsolutePath fromString(String absolutePathString) throws InvalidPathException;

        /** Creates an AbsolutePath instance from a RelativePath + the current working path (absolute path of currently opened note) */
        static AbsolutePath fromRelativePath(RelativePath relativePath, AbsolutePath currentWorkingPath) throws InvalidPathException;

        /** Transforms this absolute path to a RelativePath instance */
        RelativePath toRelativePath(AbsolutePath currentWorkingPath);

        /** Gets the individual components of the path, e.g. for "/root/CS2103T/project" they are "root", "CS2103T", and "project", in that order */
        List<String> getComponents();
      }
      ```
   - ```java
      interface RelativePath {
        /** Tests a plain string to see if it is a valid relative path */
        static boolean isValidRelativePath(String relativePathString);

        /** Creates a RelativePath instance from plain text, e.g. "../CS2103T/project" */
        static RelativePath fromString(String relativePathString) throws InvalidPathException;

        /** Creates a RelativePath instance from an AbsolutePath + the current working path (path of currently opened note) */
        static AbsolutePath fromAbsolutePath(AbsolutePath absolutePath, AbsolutePath currentWorkingPath) throws InvalidPathException;

        /** Transforms this absolute path to an AbsolutePath instance */
        AbsolutePath toAbsolutePath(AbsolutePath currentWorkingPath);

        /** Gets the individual components of the path, e.g. for "../CS2103T/project" they are "..", "CS2103T", and "project", in that order */
        List<String> getComponents();
      }
      ```
   - ```java
      class InvalidPathException extends Exception { }
      ```

#### More on the benefits of separating `AbsolutePath` and `RelativePath` into two separate classes.

I plan to provide a `correct(path)` method in `CorrectionEngine` that corrects a given `Path` based on the available `Path`s in the system. There are two possible implementations:
1. We allow the caller of the method to pass in a path string and the `CorrectionEngine` will parse + correct the path. That is, the signature of the `correct` method will be `Path correct(String pathString)`. Nevertheless, this will result in a less cohesive implementation as `CorrectionEngine` now needs to deal with the parsing of the `pathString` and the correction of the parsed `Path` object. Shouldn't `CorrectionEngine` only deals with correction-related tasks, while parsing-relating tasks be done by `Parser` or `SuggestionEngine`?
2. We allow the caller of the method to pass in a path object and the `CorrectionEngine` will only need to correct the path. That is, the signature of the `correct` method will be `Path correct(Path path)`. However, if we were to stick to the old implementation of the `Path` object, we might a `Path` that represents the path `"../CS2103/../CS2103"`, which leads back to the problem of the `CorrectionEngine` needing to parse the given path. If we were to make the `correct` method accept `AbsolutePath`s only (i.e., `AbsolutePath correct(AbsolutePath absolutePath)`), however, there is no longer a problem. This is because the `..` and `.` special keywords doesn't exist in the context of an absolute path!

### LINKED ISSUE #117: Create Absolute and Relative Path class
To create a `AbsolutePathl` and `RelativePath` concrete class which implements `Path` interface.
API proposed on issue #96

### LINKED ISSUE #118: Extension of RelativePath
This is an extension of the Issue #117.
Handle special case with "../"
e.g "CS2103/../CS2103"

### PR DESCRIPTION
**Pull request by ljiazh3ng**
resolves #117 #118 
Unable to parse relative paths with the format "../"
for example "CS2103/../CS2103"
Will open another issue for that special case.

### CODE REVIEW

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 1]
```diff
@@ -1,53 +1,113 @@
...
 import java.util.List;
+import java.util.Objects;
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
  * TODO: Add Javadoc
  */
 public class AbsolutePath implements Path {
+    public static final String INVALIDABSOLUTEPATH = "Invalid absolute path";
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Let's rewrite this as `INVALID_ABSOLUTE_PATH` instead!

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 2]
```diff
@@ -1,53 +1,113 @@
...
+        for (String obj : absolutePathString.split("/")) {
+            if (!obj.trim().equals("")) {
+                this.paths.add(obj.trim());
+            }
+        }
+    }
+
     /**
-     * TODO: Add Javadoc
+     * Check if string is a ValidAbsolutePath
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Hmm do you mean `Check if a supplied string is a valid AbosolutePath`?

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 3]
```diff
@@ -1,53 +1,113 @@
...
+     * @param absolutePathString
+     * @return
      */
     public static boolean isValidAbsolutePath(String absolutePathString) {
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java:35]: Let's use regexes to achieve this purpose! It's more [declarative](https://en.wikipedia.org/wiki/Declarative_programming) and in a way (although not always) less error-prone!

Comment (kevinputera) [reply src/main/java/com/notably/commons/core/path/AbsolutePath.java:35]: Take a look at @firzanarmani 's PR #101 to see how he structured his `isValidTitle()` method!

Comment (kevinputera) [reply src/main/java/com/notably/commons/core/path/AbsolutePath.java:35]: You can use this regex `"(\\/(\\.|\\..|\\p{Alnum}+))+\\/?"`
This matches any path of the shape `/(alphanumeric or '.' or '..')/.....`

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 4]
```diff
@@ -1,53 +1,113 @@
...
 
 /**
  * TODO: Add Javadoc
  */
 public class AbsolutePath implements Path {
+    public static final String INVALIDABSOLUTEPATH = "Invalid absolute path";
+    private final List<String> paths;
+
+
+    public AbsolutePath(String absolutePathString) {
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Let's make this constructor private? Since we're already providing factory static methods like `fromString`, `fromRelativePath`, etc.

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 5]
```diff
@@ -1,53 +1,113 @@
...
+     * @return Absolute Path.
+     * @throws InvalidPathException if String provided is not a valid absolutePath.
      */
     public static AbsolutePath fromString(String absolutePathString) throws InvalidPathException {
-        // TODO: Add implementation
-        return new AbsolutePath();
+        if (isValidAbsolutePath(absolutePathString)) {
+            return new AbsolutePath(absolutePathString);
+        } else {
+            throw new InvalidPathException(INVALIDABSOLUTEPATH);
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Just FYI: You don't actually need the `else` branch here. If the `if` branch is true, the program would have returned. For that reason, you can rewrite this as

```java
if (isValidAbsolutePath(absolutePathString)) {
  return new AbsolutePath(absolutePathString);
}
throw new InvalidPathException(INVALID_ABSOLUTE_PATH);
```

However, even better, we can structure this condition following the [happy path](https://en.wikipedia.org/wiki/Happy_path) principle, as such

```java
if (!isValidAbsolutePath(absolutePathString)) {
  throw new InvalidPathException(INVALID_ABSOLUTE_PATH);
}
return new AbsolutePath(absolutePathString);

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 6]
```diff
@@ -1,53 +1,113 @@
...
+     * @throws InvalidPathException
      */
     public static AbsolutePath fromRelativePath(RelativePath relativePath,
             AbsolutePath currentWorkingPath) throws InvalidPathException {
-        // TODO: Add implementation
-        return new AbsolutePath();
+        List<String> temp = new ArrayList<>(relativePath.getComponents());
+        List<String> temp2 = new ArrayList<>(currentWorkingPath.getComponents());
+        temp2.addAll((temp));
+        return new AbsolutePath(String.join("/", temp2));
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Hmm, I don't think this will work. For example, if the `relativePath` contains `"./CS2103/../CS2103"` and the `currentWorkingPath` contains `"/root/school"`, you'll end up getting `"/root/school/./CS2103/../CS2103"`.

Comment (kevinputera) [reply src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Instead, I think you should do something similar to the following:

1. Initialize a `newComponents` variable of type `List<String>`.
2. Similar to what you have done, get the components of the `currentWorkingPath`. Append all the components to `newComponents`.
3. Loop through the components of the `relativePath` one by one.
   1. If you encounter a "." string, ignore it.
   2. If you encounter a ".." string, pop the last element of `newComponents`.
   3. Else, add the string to `newComponents`.
4. Then, lastly, create the new `AbsolutePath` using `newComponents`. Perhaps, instead of joining these `newComponents` into a string and call the default constructor (with the string argument), you'd want to create a new constructor that accepts a `List<String>` parameter.

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 7]
```diff
@@ -1,53 +1,113 @@
...
+    @Override
+    public boolean equals(Object object) {
+        if (!(object instanceof Path)) {
+            return false;
+        }
+
+        Path another = (Path) object;
+        List<String> temp = another.getComponents();
+        return this.paths.equals(temp);
+    }
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java:115]: Nit: Add a new line below this!

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 8]
```diff
@@ -1,53 +1,113 @@
...
+    @Override
+    public int hashCode() {
+        return Objects.hash(this.paths);
+    }
+
+    @Override
+    public String toString() {
+        return (Arrays.toString(this.paths.toArray()));
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: I don't think you need to do this. By default, `List`'s `toString()` method is already propertly formatted. That is, even if you only return `paths.toString` here, everything will just look as good.

Nevertheless, perhaps you would want to consider joining the `paths` list with a `"/"` character and return the result string instead?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 9]
```diff
@@ -0,0 +1,38 @@
...
+import static org.junit.jupiter.api.Assertions.assertEquals;
+
+import org.junit.jupiter.api.Test;
+
+import com.notably.commons.core.path.exceptions.InvalidPathException;
+
+class AbsolutePathTest {
+
+    @Test
+    public void createAbsolutePath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Follow the test case method's naming convention [here](https://nus-cs2103-ay1920s2.github.io/website/coding-standards/java/intermediate.html)!

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+            assertEquals(new AbsolutePath("/CS2103/notes"), AbsolutePath.fromString("/CS2103/notes"));
+        } catch (InvalidPathException ex) {
+            System.out.println("Error");
+        }
+
+    }
+
+
+    @Test
+    public void convertAbsolutePath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Follow the test case method's naming convention [here](https://nus-cs2103-ay1920s2.github.io/website/coding-standards/java/intermediate.html)!

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 11]
```diff
@@ -0,0 +1,41 @@
...
+
+import com.notably.commons.core.path.exceptions.InvalidPathException;
+
+/**
+ * Test for RelativePath.
+ */
+class RelativePathTest {
+
+    @Test
+    public void createRelativePath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Follow the test case method's naming convention [here](https://nus-cs2103-ay1920s2.github.io/website/coding-standards/java/intermediate.html)!

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 12]
```diff
@@ -0,0 +1,41 @@
...
+            assertEquals(new RelativePath("CS2103/notes"), RelativePath.fromString("CS2103/notes"));
+        } catch (InvalidPathException ex) {
+            System.out.println("Error");
+        }
+
+    }
+
+
+    @Test
+    public void convertRelativePath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Follow the test case method's naming convention [here](https://nus-cs2103-ay1920s2.github.io/website/coding-standards/java/intermediate.html)!

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 13]
```diff
@@ -0,0 +1,38 @@
...
+class AbsolutePathTest {
+
+    @Test
+    public void createAbsolutePath() {
+        assertThrows(InvalidPathException.class, () -> AbsolutePath.fromString("CS2103/notes"));
+        try {
+            assertEquals(new AbsolutePath("/CS2103/notes"), AbsolutePath.fromString("/CS2103/notes"));
+        } catch (InvalidPathException ex) {
+            System.out.println("Error");
+        }
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: You should split this into two test cases:
1. One, you assert that without the leading `"/"` it's gonna throw
2. Another one, you assert that with the correct string the path got created successfully.

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 14]
```diff
@@ -0,0 +1,38 @@
...
+        AbsolutePath currPath = new AbsolutePath("/CS2103");
+        RelativePath relativePath = new RelativePath("notes/hello");
+        try {
+            AbsolutePath expectedAbsolutePath = new AbsolutePath("/CS2103/notes/hello");
+            assertEquals(expectedAbsolutePath, AbsolutePath.fromRelativePath(relativePath, currPath));
+            assertEquals(new RelativePath("notes/hello"), absolutePath.toRelativePath(currPath));
+        } catch (InvalidPathException ex) {
+            System.out.println("Error");
+        }
+
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java:51]: Just FYI!

I believe usually test cases are organized this way (can't remember where I read about it, so please take this advice with a grain of salt LOL):
1. Setup all the parameters used in the assertions
2. Setup all the expected variables
3. Do the assertions

You can take a look at my PR #110, I basically organized it that way!

**Review by kevinputera — CHANGES_REQUESTED** [review]
Hey @ljiazh3ng ! I added comments mostly on the `AbsolutePath`-related classes, but I believe most of them can be applied to both `AbsolutePath` and `RelativePath`-related classes too!

Please let me know what you think :)

**Comment by ljiazh3ng** [comment]
Thank you for the detailed feedback @kevinputera , i have made the necessary adjustments. Do let me know if i missed anything!

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 15]
```diff
@@ -1,53 +1,123 @@
...
+import java.util.Objects;
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
  * TODO: Add Javadoc
  */
 public class AbsolutePath implements Path {
+    public static final String INVALID_ABSOLUTE_PATH = "Invalid absolute path";
+    public static final String VALIDATION_REGEX = "(\\/(\\p{Alnum}+))+\\/?";
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Sorry for giving a wrong regex expression 😅

Just FYI: This can also be rewritten as `"(\\/\\p{Alnum}+)+\\/?"`! The [capturing group](https://www.regular-expressions.info/brackets.html) between `\\p{Alnum}+` is not necessary here

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 16]
```diff
@@ -1,53 +1,123 @@
...
+    public AbsolutePath(List<String> absolutePathList) {
+        this.paths = absolutePathList;
+    }
+
     /**
-     * TODO: Add Javadoc
+     * Check if a supplied string is a ValidAbsolutePath
+     * @param absolutePathString
+     * @return
      */
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java:34]: Do you mean `Check if a supplied string is a valid AbosolutePath?`

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 17]
```diff
@@ -1,53 +1,123 @@
...
 
+import java.util.ArrayList;
 import java.util.List;
+import java.util.Objects;
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
  * TODO: Add Javadoc
  */
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Let's add a Javadoc for `AbsolutePath` here?

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 18]
```diff
@@ -1,53 +1,123 @@
...
      */
     public static AbsolutePath fromString(String absolutePathString) throws InvalidPathException {
-        // TODO: Add implementation
-        return new AbsolutePath();
+        if (isValidAbsolutePath(absolutePathString)) {
+            return new AbsolutePath(absolutePathString);
+        } else {
+            throw new InvalidPathException(INVALID_ABSOLUTE_PATH);
+        }
     }
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: I added this comment before in a previous review. Thinking about it, I believe you should do the change since this principle is introduced during one of the lectures about clean code.

You don't actually need the else branch here. If the if branch is true, the program would have returned. For that reason, you can rewrite this as

```java
if (isValidAbsolutePath(absolutePathString)) {
  return new AbsolutePath(absolutePathString);
}
throw new InvalidPathException(INVALID_ABSOLUTE_PATH);
```

However, even better, we can structure this condition following the happy path principle, as such

```java
if (!isValidAbsolutePath(absolutePathString)) {
  throw new InvalidPathException(INVALID_ABSOLUTE_PATH);
}
return new AbsolutePath(absolutePathString);
```

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 19]
```diff
@@ -1,53 +1,123 @@
...
             AbsolutePath currentWorkingPath) throws InvalidPathException {
-        // TODO: Add implementation
-        return new AbsolutePath();
+        List<String> temp = new ArrayList<>(relativePath.getComponents());
+        List<String> temp2 = new ArrayList<>(currentWorkingPath.getComponents());
+        for (String obj : temp) {
+            if (obj.equals("..")) {
+                if (temp.remove(temp2.size() - 1) == null) {
+                    throw new InvalidPathException("Empty directory");
+                }
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: I believe that this should be `temp2.remove` instead of `temp.remove`?

In addition, do a size checking for `temp2` before doing the removal. Otherwise, if `temp2.remove` might throw an `IndexOutOfBoundsException`

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 20]
```diff
@@ -1,53 +1,123 @@
...
+    private AbsolutePath(String absolutePathString) {
+        this.paths = new ArrayList<>();
+        for (String obj : absolutePathString.split("/")) {
+            if (!obj.trim().equals("")) {
+                this.paths.add(obj.trim());
+            }
+        }
+    }
+
+    public AbsolutePath(List<String> absolutePathList) {
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java:26]: Let's make this a `private` constructor?

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 21]
```diff
@@ -1,53 +1,123 @@
...
+     * @return the converted RelativePath
      */
-    public RelativePath toRelativePath(AbsolutePath currentWorkingPath) {
-        // TODO: Add implementation
-        return new RelativePath();
+    public RelativePath toRelativePath(AbsolutePath currentWorkingPath) throws InvalidPathException {
+        int sizeOfCurrent = currentWorkingPath.getComponents().size();
+        if (sizeOfCurrent < this.getComponents().size()) {
+            throw new InvalidPathException("Current working path bigger than AbsolutePath");
+        }
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: This path should not throw an error. For example, if the current working directory is `"/root/hello"` and the current path object is pointing to `"/root/hello/1234"`, you should create the `"./1234"` or `"1234"` relative path.

The converse is true. If the current working directory is `"/root/hello"` and the current path object is pointing to `"/root"`, you should create the `".."` relative path.

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 22]
```diff
@@ -1,53 +1,123 @@
...
+        List<String> temp = this.paths.subList(sizeOfCurrent, this.paths.size());
+        String relativePathString = String.join("/", temp);
+        return RelativePath.fromString(relativePathString);
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Actually, this feels rather funny to me after thinking about it, since we are joining back the components to a string before passing it to `RelativePath.fromString`, which is going to break up the string again to the constituent components.

Let's add the static methods `AbsolutePath.fromComponents` and `RelativePath.fromComponents` instead?

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 23]
```diff
@@ -1,53 +1,123 @@
...
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
  * TODO: Add Javadoc
  */
 public class AbsolutePath implements Path {
+    public static final String INVALID_ABSOLUTE_PATH = "Invalid absolute path";
+    public static final String VALIDATION_REGEX = "(\\/(\\p{Alnum}+))+\\/?";
+    private final List<String> paths;
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Oh yes, let's rename this variable to `components`? So that the method `getComponents` feels more natural.

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 24]
```diff
@@ -1,53 +1,112 @@
...
 
+import java.util.ArrayList;
 import java.util.List;
+import java.util.Objects;
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
  * TODO: Add Javadoc
  */
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: Let's add a Javadoc for `RelativePath` here?

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 25]
```diff
@@ -1,53 +1,112 @@
...
 public class RelativePath implements Path {
+    public static final String INVALID_RELATIVE_PATH = "Invalid relative path";
+    public static final String VALIDATION_REGEX = "((\\.|\\..|\\p{Alnum}+))+\\/?";
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: There is a bug in this `VALIDATION_REGEX`! It won't correctly match the `"asdfkj/sdfljk/asdlfkj"` path, for example, as the `/` characters between components are not detected!

Instead, we should rectify this as `"(\\.|\\..|\\p{Alnum}+)(\\/(\\.|\\..|\\p{Alnum}+))*\\/?"`

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 26]
```diff
@@ -1,53 +1,112 @@
...
+    private final List<String> paths;
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: Same as above, let's rename this variable as `components`?

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 27]
```diff
@@ -1,53 +1,112 @@
...
+                    throw new InvalidPathException("Root block does not have a parent");
+                }
+            } else if (obj.equals(".")) {
+                // Do nothing
+            } else {
+                temp2.add(obj);
+            }
+        }
+        return new AbsolutePath(temp2);
     }
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: You should be able to just call `AbsolutePath.fromRelativePath(this, currentWorkingPath)` here!

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 28]
```diff
@@ -1,53 +1,112 @@
...
+     * @param absolutePath to convert to relative path.
+     * @param currentWorkingPath of the current working directory.
+     * @return the converted relative path.
+     * @throws InvalidPathException
      */
     public static RelativePath fromAbsolutePath(AbsolutePath absolutePath,
             AbsolutePath currentWorkingPath) throws InvalidPathException {
-        // TODO: Add implementation
-        return new RelativePath();
+        return absolutePath.toRelativePath(currentWorkingPath);
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: Should we move `AbsolutePath`'s `toRelativePath`'s implementation here instead?

Then, over there in `AbsolutePath`'s `toRelativePath` method we can call `RelativePath.fromAbsolutePath(this, currentWorkingPath)`!

The rationale of moving the implementation there down here is to keep consistent with how `AbsolutePath.fromRelativePath` and `RelativePath`'s `toAbsolutePath` interact!

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 29]
```diff
@@ -1,53 +1,112 @@
...
+    public static final String VALIDATION_REGEX = "((\\.|\\..|\\p{Alnum}+))+\\/?";
+    private final List<String> paths;
+    private RelativePath(String relativePathString) {
+        this.paths = new ArrayList<>();
+        for (String obj : relativePathString.split("/")) {
+            if (!obj.trim().equals("")) {
+                this.paths.add(obj.trim());
+            }
+        }
+    }
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: @ljiazh3ng wanna discuss with you about this!

Say if our user inputs the `"CS2103/../CS2103/hello"` string to this constructor. Would you prefer if we:
1. Keep it as is. That is, the components will content ["CS2103", "..", "CS2103", "hello"], or
2. Simplify the path. That is, we do something similar to the thing we do in`AbsolutePath.fromRelativePath` and store the components as ["hello"] (since `"CS2103/../CS2103"` cancels each other out)

Which one?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 30]
```diff
@@ -0,0 +1,82 @@
...
+import org.junit.jupiter.api.Test;
+
+import com.notably.commons.core.path.exceptions.InvalidPathException;
+
+
+class AbsolutePathTest {
+
+    @Test
+    public void createAbsolutePath_validInputString_generateAbsolutePath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Hmmm, two things:
1. You can actually don't care about the exception here. Just make the `createAbsolutePath_validInputString_generateAbsolutePath` method throws `InvalidPathException` since you know for sure that this method shouldn't throw if it functions correctly.
2. I don't think testing the correct creation of `AbsolutePath` this way actually tests anything significant. That is because we know both `expectedOutput` and `testInput` are created (either explicitly or implicitly) using `AbsolutePath`'s constructor! Instead, I propose we do the testing as such:

```java
final String pathString = "/CS2103/notes";

final List<String> expectedComponents = List.of("CS2103", "notes");

AbsolutePath createdPath = AbsolutePath.fromString(pathString);
List<String> createdComponents = createdPath.getComponents();
assertEquals(expectedComponents, createdComponents);
```

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 31]
```diff
@@ -0,0 +1,82 @@
...
+        assertThrows(InvalidPathException.class, () -> AbsolutePath.fromString("CS2103/notes"));
+    }
+
+    @Test
+    public void createAbsolutePath_invalidInputString2_exceptionThrown() {
+        assertThrows(InvalidPathException.class, () -> AbsolutePath.fromString("/../CS2103/notes"));
+    }
+
+    @Test
+    public void convertAbsoluteToRelativePath_validInput_correctedPath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here! You can just make the method `throws InvalidPathException`.

However, the testing implementation part looks good here!

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 32]
```diff
@@ -0,0 +1,82 @@
...
+            assertEquals(expectedOutput, inputAbsolutePath.toRelativePath(inputCurrPath));
+        } catch (InvalidPathException ex) {
+            ex.getMessage();
+        }
+    }
+
+    @Test
+    public void createAbsolutePathFromRelativePath_validInput_convertedAbsolutePath() {
+        try {
+            final RelativePath inputRelPath = RelativePath.fromString("/../../hello");
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Erm. This doesn't seem like a correct relative path string hahaha

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 33]
```diff
@@ -0,0 +1,82 @@
...
+            final RelativePath expectedOutput = RelativePath.fromString("notes/hello");
+
+            assertEquals(expectedOutput, inputAbsolutePath.toRelativePath(inputCurrPath));
+        } catch (InvalidPathException ex) {
+            ex.getMessage();
+        }
+    }
+
+    @Test
+    public void createAbsolutePathFromRelativePath_validInput_convertedAbsolutePath() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here, just `throws InvalidPathException`. Just realised this below. By catching the error, you accidentally silenced `RelativePath.fromString`'s exception when you called it with the wrong path string

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 34]
```diff
@@ -0,0 +1,82 @@
...
+            assertEquals(expectedPaths, AbsolutePath.fromRelativePath(inputRelPath, inputCurrPath).getComponents());
+        } catch (InvalidPathException ex) {
+            ex.getMessage();
+        }
+    }
+
+    @Test
+    public void createAbsolutePathFromRelativePath_invalidInput_exceptionThrown() {
+        try {
+            final RelativePath inputRelPath = RelativePath.fromString("/../../hello");
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here! Invalid string

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 35]
```diff
@@ -0,0 +1,61 @@
...
+import java.util.List;
+
+import org.junit.jupiter.api.Test;
+
+import com.notably.commons.core.path.exceptions.InvalidPathException;
+
+/**
+ * Test for RelativePath.
+ */
+class RelativePathTest {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java:16]: Same comments for the test cases below!

**Review by kevinputera — CHANGES_REQUESTED** [review]
Hey @ljiazh3ng ! Left some comments below. Let's finish this class soon!

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 36]
```diff
@@ -1,53 +1,127 @@
...
 
+import java.util.ArrayList;
 import java.util.List;
+import java.util.Objects;
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
- * TODO: Add Javadoc
+ * Represents a Path to the block that take reference from the Root node.
```
Comment (HemanshuGandhi) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java]: Do you think it would be clearer English to say "Represents the Path to a Block, starting from the Root node."

File: src/main/java/com/notably/commons/core/path/AbsolutePath.java [hunk 37]
```diff
@@ -1,53 +1,127 @@
...
+    private AbsolutePath(String absolutePathString) {
+        this.components = new ArrayList<>();
+        for (String obj : absolutePathString.split("/")) {
+            if (!obj.trim().equals("")) {
+                this.components.add(obj.trim());
+            }
+        }
+    }
+
+    public AbsolutePath(List<String> absolutePathList) {
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/AbsolutePath.java:26]: Let's make this a private constructor too?

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 38]
```diff
@@ -1,53 +1,143 @@
...
 
 import com.notably.commons.core.path.exceptions.InvalidPathException;
 
 /**
- * TODO: Add Javadoc
+ * Represents a path to the block relative to the current directory.
  */
 public class RelativePath implements Path {
+    public static final String INVALID_RELATIVE_PATH = "Invalid relative path";
+    public static final String VALIDATION_REGEX = "(\\.|\\..|\\p{Alnum}+)(/(\\.|\\..|\\p{Alnum}+))*\\/?";
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java]: There is an error in the regex. It should be `(\\.|\\..|\\p{Alnum}+)(\\/(\\.|\\..|\\p{Alnum}+))*\\/?`

File: src/main/java/com/notably/commons/core/path/RelativePath.java [hunk 39]
```diff
@@ -1,53 +1,143 @@
...
+    private final List<String> components;
+    private RelativePath(String relativePathString) {
```
Comment (kevinputera) [inline src/main/java/com/notably/commons/core/path/RelativePath.java:17]: Nit: Whitespace before this line? Just to clearly organize the code (logical separation between fields and constructors) haha

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 40]
```diff
@@ -0,0 +1,64 @@
...
+
+import org.junit.jupiter.api.Test;
+
+import com.notably.commons.core.path.exceptions.InvalidPathException;
+
+
+class AbsolutePathTest {
+
+    @Test
+    public void createAbsolutePath_validInputString_generateAbsolutePath() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Let's rename this method to `fromString_validInputString_generateAbsolutePath()` to follow the convention laid out [here](https://nus-cs2103-ay1920s2.github.io/website/coding-standards/java/intermediate.html)?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 41]
```diff
@@ -0,0 +1,64 @@
...
+
+        List<String> paths = new ArrayList<>();
+        paths.add("CS2103");
+        paths.add("notes");
+
+        assertEquals(paths, testInput.getComponents());
+    }
+
+    @Test
+    public void createAbsolutePath_invalidInputString1_exceptionThrown() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here, let's rename to `fromString_invalidInputString1_exceptionThrown`?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 42]
```diff
@@ -0,0 +1,64 @@
...
+        assertThrows(InvalidPathException.class, () -> AbsolutePath.fromString("CS2103/notes"));
+    }
+
+    @Test
+    public void createAbsolutePath_invalidInputString2_exceptionThrown() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here, let's rename to `fromString_invalidInputString2_exceptionThrown`?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 43]
```diff
@@ -0,0 +1,64 @@
...
+        assertThrows(InvalidPathException.class, () -> AbsolutePath.fromString("/../CS2103/notes"));
+    }
+
+    @Test
+    public void convertAbsoluteToRelativePath_validInput_correctedPath() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here, let's rename to `toRelativePath_validInput_correctedPath`?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 44]
```diff
@@ -0,0 +1,64 @@
...
+        final AbsolutePath inputAbsolutePath = AbsolutePath.fromString("/CS2103/notes/hello");
+        final AbsolutePath inputCurrPath = AbsolutePath.fromString("/CS2103");
+
+        final RelativePath expectedOutput = RelativePath.fromString("notes/hello");
+
+        assertEquals(expectedOutput, inputAbsolutePath.toRelativePath(inputCurrPath));
+    }
+
+    @Test
+    public void createAbsolutePathFromRelativePath_validInput_convertedAbsolutePath() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here, let's rename to `fromRelativePath_validInput_convertedAbsolutePath`?

File: src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java [hunk 45]
```diff
@@ -0,0 +1,64 @@
...
+        final AbsolutePath inputCurrPath = AbsolutePath.fromString("/CS2103/filler");
+
+        List<String> expectedPaths = new ArrayList<>();
+        expectedPaths.add("hello");
+
+        assertEquals(expectedPaths, AbsolutePath.fromRelativePath(inputRelPath, inputCurrPath).getComponents());
+    }
+
+    @Test
+    public void createAbsolutePathFromRelativePath_invalidInput_exceptionThrown() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/AbsolutePathTest.java]: Same here, let's rename to `fromRelativePath_invalidInput_exceptionThrown`?

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 46]
```diff
@@ -0,0 +1,57 @@
...
+
+    @Test
+    public void createRelativePath_validInputString_generateAbsolutePath() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Same here, let's rename to `fromString_validInputString_generateAbsolutePath`?

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 47]
```diff
@@ -0,0 +1,57 @@
...
+        final RelativePath testInput = RelativePath.fromString("CS2103/notes");
+        List<String> paths = new ArrayList<>();
+        paths.add("CS2103");
+        paths.add("notes");
+        assertEquals(paths, testInput.getComponents());
+    }
+
+    @Test
+    public void createAbsolutePath_invalidInputString_exceptionThrown() {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Same here, let's rename to `fromString_invalidInputString_exceptionThrown`?

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 48]
```diff
@@ -0,0 +1,57 @@
...
+        assertThrows(InvalidPathException.class, () -> RelativePath.fromString("/CS2103/notes"));
+    }
+
+    @Test
+    public void convertRelativeToAbsolutePath_validInput_correctedPath() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Same here, let's rename to `toAbsolutePath_validInput_correctedPath`?

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 49]
```diff
@@ -0,0 +1,57 @@
...
+        final RelativePath inputRelativePath = RelativePath.fromString("CS2103/notes/hello");
+        final AbsolutePath inputCurrPath = AbsolutePath.fromString("/CS2103");
+
+        final AbsolutePath expectedOutput = AbsolutePath.fromString("/CS2103/CS2103/notes/hello");
+
+        assertEquals(expectedOutput, inputRelativePath.toAbsolutePath(inputCurrPath));
+    }
+
+    @Test
+    public void convertRelativePath_invalidInput_exceptionThrown() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Same here, let's rename to `toAbsolutePath_invalidInput_exceptionThrown`?

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 50]
```diff
@@ -0,0 +1,57 @@
...
+
+    @Test
+    public void convertRelativeToAbsolutePath_validInput_correctedPath() throws InvalidPathException {
+        final RelativePath inputRelativePath = RelativePath.fromString("CS2103/notes/hello");
+        final AbsolutePath inputCurrPath = AbsolutePath.fromString("/CS2103");
+
+        final AbsolutePath expectedOutput = AbsolutePath.fromString("/CS2103/CS2103/notes/hello");
+
+        assertEquals(expectedOutput, inputRelativePath.toAbsolutePath(inputCurrPath));
+    }
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java:40]: I think you should add another test case for `toAbsolutePath` that involve the `..` or `.` element in the relative path components.

File: src/test/java/com/notably/commons/core/Path/RelativePathTest.java [hunk 51]
```diff
@@ -0,0 +1,57 @@
...
+    @Test
+    public void convertRelativePath_invalidInput_exceptionThrown() throws InvalidPathException {
+        final RelativePath inputRelativePath = RelativePath.fromString("../../notes/hello");
+        final AbsolutePath inputCurrPath = AbsolutePath.fromString("/CS2103");
+
+        assertThrows(InvalidPathException.class, () -> inputRelativePath.toAbsolutePath(inputCurrPath));
+    }
+
+    @Test
+    public void equalsRelativePath_similarPath_pathAreEqual() throws InvalidPathException {
```
Comment (kevinputera) [inline src/test/java/com/notably/commons/core/Path/RelativePathTest.java]: Same here, let's rename to `equals_similarPath_pathAreEqual`?

**Review by kevinputera — APPROVED** [review]
Hey @ljiazh3ng ! Looks really great! I'm approving this so that you can merge directly after the changes are made.
Some final comments I have are listed below!

If you want to add more test cases, you can consider testing more invalid paths through the `fromString` methods. For example, you can assert that non-alphanumeric characters will throw an error, `"//"` will throw an error, etc.

Another possible improvement is to make the `fromComponents` static method throw `InvalidPathException` if the individual components don't make sense for the `...Path` that is created. For example, for `AbsolutePath`s, only alphanumeric components should be accepted!

File: src/main/java/com/notably/commons/core/path/RelativePath.java (hunk 38 above)
Comment (kevinputera) [reply src/main/java/com/notably/commons/core/path/RelativePath.java]: For whatever reason, this error in regex does not get caught by the test cases. Any ideas why 🤔 ?
