### PR TITLE
Exception handling for parser

### LINKED ISSUE #270: More thorough exception handling in the Parser-Command layer
Currently, we don't catch enough exceptions inside any of the `Command` classes.

For example, try running `new -t Notably -b Body` after another note titled `Notably` existed. You'll see that the console is printing out the error stack of the uncaught exception.

Try running `delete -t /` or `edit -b asdf` while you're in the Root and you'll see something similar.

The point is, let's improve the exception handling at the Parser-Command layer

### PR DESCRIPTION
**Pull request by ljiazh3ng**
resolves #270 
Previously runtime exceptions created at the BlockImpl were not handled/caught by the parser.
This PR handles the following exception:
- [x] `CannotModifyRootException`
- [x] `DuplicateBlockException`
- [x] `NoSuchBlockException`

The listed exceptions are caught when the `new`, `edit`, `delete`, `open` executes.

### CODE REVIEW

File: src/main/java/com/notably/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -20,13 +23,17 @@ public DeleteCommand(Path targetPath) {
...
 
     @Override
-    public void execute(Model notablyModel) {
-        requireNonNull(notablyModel);
-        if (this.targetPath instanceof RelativePath) {
-            RelativePath toConvert = (RelativePath) this.targetPath;
-            this.targetPath = toConvert.toAbsolutePath(notablyModel.getCurrentlyOpenPath());
+    public void execute(Model notablyModel) throws CommandException {
+        try {
+            requireNonNull(notablyModel);
```
Comment (kevinputera) [inline src/main/java/com/notably/logic/commands/DeleteCommand.java]: Let's move this nullity check out of the try

File: src/main/java/com/notably/logic/commands/DeleteCommand.java [hunk 2]
```diff
@@ -20,13 +23,17 @@ public DeleteCommand(Path targetPath) {
...
+            if (this.targetPath instanceof RelativePath) {
+                RelativePath toConvert = (RelativePath) this.targetPath;
+                this.targetPath = toConvert.toAbsolutePath(notablyModel.getCurrentlyOpenPath());
+            }
```
Comment (kevinputera) [inline src/main/java/com/notably/logic/commands/DeleteCommand.java]: Let's move this section out of the try-catch block for clarity! I believe it makes clearer that it's the code below (`removeBlock`) that might throw the errors you'd like to catch

File: src/main/java/com/notably/logic/commands/EditCommand.java [hunk 3]
```diff
@@ -24,9 +26,13 @@ public EditCommand(Body body) {
      * @param notablyModel used to access the tree structure.
      * @throws CommandException
      */
-    public void execute(Model notablyModel) {
+    public void execute(Model notablyModel) throws CommandException {
         requireNonNull(notablyModel);
-        notablyModel.updateCurrentlyOpenBlockBody(body);
+        try {
+            notablyModel.updateCurrentlyOpenBlockBody(body);
+        } catch (NoSuchBlockException | CannotModifyRootException ex) {
```
Comment (kevinputera) [inline src/main/java/com/notably/logic/commands/EditCommand.java]: Actually I think we won't encounter any `NoSuchBlockException` here? But let's leave it just in case.

File: src/main/java/com/notably/logic/commands/NewCommand.java [hunk 4]
```diff
@@ -29,10 +30,13 @@ public NewCommand(Block block, AbsolutePath path) {
      */
     public void execute(Model notablyModel) throws CommandException {
         requireNonNull(notablyModel);
-
-        if (notablyModel.hasPath(this.path)) {
-            throw new CommandException("Block with the same Title detected.");
+        try {
+            if (notablyModel.hasPath(this.path)) {
+                throw new CommandException("Block with the same Title detected.");
+            }
```
Comment (kevinputera) [inline src/main/java/com/notably/logic/commands/NewCommand.java]: We can actually remove this portion right, if my understanding is correct?

File: src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java [hunk 5]
```diff
@@ -78,8 +79,12 @@ public void execute(Model model) {
                             int frequency = blockBodies.length - 1;
                             String displayText = absolutePath.getStringRepresentation();
                             Runnable action = () -> {
-                                OpenCommand openCommand = new OpenCommand(absolutePath);
-                                openCommand.execute(model);
+                                try {
+                                    OpenCommand openCommand = new OpenCommand(absolutePath);
+                                    openCommand.execute(model);
+                                } catch (CommandException ex) {
+                                    throw new RuntimeException(ex.getMessage());
```
Comment (kevinputera) [inline src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java]: Actually, should we throw an `AssertionError` here, just to be specific? Also, let's add an inline comment here to explain why there shouldn't be any error while executing the `openCommand`? @johannagwan Please advise!

**Review by kevinputera — COMMENTED** [review]
LGTM! Some comments below. @johannagwan Please help check the `SearchSuggestionCommand` portion!

File: src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java (hunk 5 above)
Comment (johannagwan) [reply src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java]: thanks @kevinputera for pointing this out! 

Regarding why there shouldn't be any error while executing the `OpenCommand`: When the user searches based on a keyword, the notes suggested will definitely be able to be opened as the block actually exists, so `NoSuchBlockException` will not be thrown. Thus, the `AssertionError` (or `RuntimeException`) should never be called. So yehhh it's good if we can add the rationale here.

Thanks for the sik werk @ljiazh3ng !

**Review by johannagwan — APPROVED** [review]

File: src/main/java/com/notably/logic/commands/DeleteCommand.java (hunk 2 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/commands/DeleteCommand.java]: done!

File: src/main/java/com/notably/logic/commands/EditCommand.java (hunk 3 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/commands/EditCommand.java]: oh yes, i've removed it.

File: src/main/java/com/notably/logic/commands/NewCommand.java (hunk 4 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/commands/NewCommand.java]: Yes it was redundant.

File: src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java (hunk 5 above)
Comment (ljiazh3ng) [reply src/main/java/com/notably/logic/commands/suggestion/SearchSuggestionCommand.java]: Roger, will change it to Assertion Error
